In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('../artifacts/transformed_data/X_train.csv')

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154858 entries, 0 to 154857
Data columns (total 9 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   carat    154858 non-null  float64
 1   depth    154858 non-null  float64
 2   table    154858 non-null  float64
 3   x        154858 non-null  float64
 4   y        154858 non-null  float64
 5   z        154858 non-null  float64
 6   cut      154858 non-null  float64
 7   color    154858 non-null  float64
 8   clarity  154858 non-null  float64
dtypes: float64(9)
memory usage: 10.6 MB


In [7]:
data = pd.read_csv('../Data/raw.csv')

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193573 entries, 0 to 193572
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   id       193573 non-null  int64  
 1   carat    193573 non-null  float64
 2   cut      193573 non-null  object 
 3   color    193573 non-null  object 
 4   clarity  193573 non-null  object 
 5   depth    193573 non-null  float64
 6   table    193573 non-null  float64
 7   x        193573 non-null  float64
 8   y        193573 non-null  float64
 9   z        193573 non-null  float64
 10  price    193573 non-null  int64  
dtypes: float64(6), int64(2), object(3)
memory usage: 16.2+ MB


In [ ]:
# train split 
from sklearn.

In [3]:
import pandas as pd

In [4]:
X_train = pd.read_csv('../artifacts/transformed/X_train.csv')
y_train = pd.read_csv('../artifacts/transformed/y_train.csv')

In [5]:
print(X_train.shape)
print(y_train.shape)

(154858, 9)
(154858, 1)


In [7]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Example target vector y
y = np.array([[1], [2], [3], [4]])
print(y.shape)

# Reshape y to (n_samples,)
y = y.ravel()  # Or y = y.flatten()
print(y.shape)
# Now y has the shape (n_samples,)
print(y.shape)

# Fit the model
model = LinearRegression()



(4, 1)
(4,)
(4,)


: 

In [1]:
import pandas as pd

# Example DataFrame
data = {'Feature1': [1, 2, 3],
        'Feature2': [4, 5, 6],
        'Feature3': [7, 8, 9],
        'Feature4': [10, 11, 12],
        'Feature5': [13, 14, 15]}

df = pd.DataFrame(data)

# Convert DataFrame to NumPy array
numpy_array = df.values
print(numpy_array)

[[ 1  4  7 10 13]
 [ 2  5  8 11 14]
 [ 3  6  9 12 15]]


In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.datasets import fetch_california_housing

In [2]:
# Load the dataset
data = fetch_california_housing()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

In [3]:
# Display the first few rows of the dataframe
print(df.head())

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422  


In [4]:
# Separate the independent variables (X) and the dependent variable (y)
X = df.drop(columns=['target'])
y = df['target']

In [5]:
print(X.shape)
print(y.shape)

(20640, 8)
(20640,)


In [6]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
# Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [8]:
# Make predictions
y_pred = model.predict(X_test)

In [9]:
# Calculate performance metrics
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [10]:
print(f"Mean Squared Error: {mse}")
print(f"R^2 Score: {r2}")

Mean Squared Error: 0.555891598695244
R^2 Score: 0.5757877060324511


In [11]:
# diffrent betwwen (10, 1) and (10,) in shape 
import numpy as np

# Create a 2D array with shape (10, 1)
array1 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
print(array1.shape)

(10, 1)


In [12]:
# Create a 1D array with shape (10,)
array2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(array2.shape)

(10,)


In [19]:
y_train = pd.read_csv('../artifacts/transformed/y_train.csv')
y_train.shape

(154858, 1)

In [22]:
# y_train DataFrame to NumPy array
y_train.flatten().shape

(154858,)

(154858, 1)

In [23]:
y_train

array([[ 614],
       [7002],
       [9347],
       ...,
       [7209],
       [ 816],
       [ 408]], dtype=int64)

In [24]:
y_train.shape

(154858, 1)

In [25]:
y_train = y_train.flatten()

In [26]:
y_train.shape

(154858,)

In [27]:
y_train

array([ 614, 7002, 9347, ..., 7209,  816,  408], dtype=int64)